DROP SCHEMA IF EXISTS DNAUTHORIZATION CASCADE;
-- СОЗДАНИЕ СХЕМЫ
CREATE SCHEMA IF NOT EXISTS DNAUTHORIZATION;
-- ТАБЛИЦА DNAUTHORIZATION.USERS_ACCOUNT
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.USERS_ACCOUNT
(
    ACCOUNT_ID                      UUID      DEFAULT GEN_RANDOM_UUID() PRIMARY KEY,
    ACCOUNT_NAME                    TEXT                                NOT NULL UNIQUE,
    ACCOUNT_MAIL                    TEXT                                NOT NULL UNIQUE,
    ACCOUNT_PASSWORD_VERIFIER       TEXT                                NOT NULL,
    ACCOUNT_SALT                    TEXT                                NOT NULL,
    ACCOUNT_LAST_PASSWORD_UPDATE    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACCOUNT_PASSWORD_RESET_INTERVAL INTEGER   DEFAULT 0                 NOT NULL,
    ACCOUNT_IS_DEPRECATED           BOOLEAN   DEFAULT FALSE             NOT NULL
);
-- ДОБАВЛЕНИЕ КОММЕНТАРИЕВ К ТАБЛИЦЕ DNAUTHORIZATION.USERS_ACCOUNT И ЕЁ СТОЛБЦАМ
COMMENT ON TABLE DNAUTHORIZATION.USERS_ACCOUNT IS 'Таблица для хранения информации о учетных записях';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_ID IS 'Уникальный идентификатор учетной записи';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_NAME IS 'Имя учетной записи пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_MAIL IS 'Электронная почта учетной записи пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_PASSWORD_VERIFIER IS 'Верификатор пароля учетной записи';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_SALT IS 'Случайная строка, используемая для хеширования пароля';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_LAST_PASSWORD_UPDATE IS 'Дата и время последнего обновления пароля';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_PASSWORD_RESET_INTERVAL IS 'Интервал сброса пароля в днях';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_ACCOUNT.ACCOUNT_IS_DEPRECATED IS 'Признак того что аккаунт удален';
-- ТАБЛИЦА DNAUTHORIZATION.USERS_INFO
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.USERS_INFO
(
    ACCOUNT_ID           UUID    NOT NULL UNIQUE REFERENCES DNAUTHORIZATION.USERS_ACCOUNT (ACCOUNT_ID),
    USER_SURNAME         TEXT    NOT NULL,
    USER_NAME            TEXT    NOT NULL,
    USER_PATRONYMIC      TEXT    NOT NULL,
    USER_DATE_OF_BIRTH   DATE    NOT NULL,
    USER_PERSONAL_NUMBER INTEGER NOT NULL UNIQUE,
    USER_STRUCTURE       INTEGER NOT NULL,
    USER_CURRENT_POST    UUID    NOT NULL,
    USER_PHONE           TEXT    NOT NULL,
    USER_OFFICE          TEXT    NOT NULL
);
-- ДОБАВЛЕНИЕ КОММЕНТАРИЕВ К ТАБЛИЦЕ DNAUTHORIZATION.USERS_INFO И ЕЁ СТОЛБЦАМ
COMMENT ON TABLE DNAUTHORIZATION.USERS_INFO IS 'Таблица для хранения дополнительной информации о пользователях';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.ACCOUNT_ID IS 'Идентификатор учетной записи пользователя (внешний ключ)';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_SURNAME IS 'Фамилия пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_NAME IS 'Имя пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_PATRONYMIC IS 'Отчество пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_DATE_OF_BIRTH IS 'Дата рождения пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_PERSONAL_NUMBER IS 'Персональный номер пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_STRUCTURE IS 'Идентификатор структуры или подразделения, к которому относится пользователь';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_CURRENT_POST IS 'Идентификатор текущей должности пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_PHONE IS 'Номер телефона пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.USERS_INFO.USER_OFFICE IS 'Офис, в котором работает пользователь';
-- ТАБЛИЦА DNAUTHORIZATION.ACTIVE_SESSIONS
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.ACTIVE_SESSIONS
(
    SESSION_ID                 TEXT                                NOT NULL UNIQUE,
    SESSION_KEY                TEXT                                NOT NULL,
    SESSION_START              TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    SESSION_ACCOUNT_ID         UUID REFERENCES DNAUTHORIZATION.USERS_ACCOUNT (ACCOUNT_ID),
    SESSION_SERVER_PRIVATE_KEY TEXT,
    SESSION_SERVER_PUBLIC_KEY  TEXT,
    SESSION_ACCOUNT_PUBLIC_KEY TEXT,
    SESSION_SCRAMBLER          TEXT,
    SESSION_AUTHORIZATION_KEY  TEXT,
    SESSION_IP_ADDRESS         TEXT,
    SESSION_SIGNATURE          TEXT,
    SESSION_LAST_ACTIVITY      TIMESTAMP,
    SESSION_CONFIRM            BOOLEAN,
    SESSION_TOKEN              TEXT
);
-- ДОБАВЛЕНИЕ КОММЕНТАРИЕВ К ТАБЛИЦЕ DNAUTHORIZATION.ACTIVE_SESSIONS И ЕЁ СТОЛБЦАМ
COMMENT ON TABLE DNAUTHORIZATION.ACTIVE_SESSIONS IS 'таблица для отслеживания активных сеансов пользователей';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_ID IS 'уникальный идентификатор сеанса';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_KEY IS 'ключ сеанса для аутентификации';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_START IS 'дата и время начала сеанса';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_ACCOUNT_ID IS 'идентификатор учетной записи, связанной с сеансом (внешний ключ)';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_SERVER_PRIVATE_KEY IS 'закрытый ключ сервера, связанный с сеансом';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_SERVER_PUBLIC_KEY IS 'публичный ключ сервера, связанный с сеансом';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_ACCOUNT_PUBLIC_KEY IS 'публичный ключ учетной записи, связанный с сеансом';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_SCRAMBLER IS 'значение для шифрования и смешивания данных сеанса';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_AUTHORIZATION_KEY IS 'ключ авторизации для доступа к ресурсам сеанса';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_SIGNATURE IS 'Сиганутра пользователя';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_LAST_ACTIVITY IS 'Последняя активность в сессии';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_CONFIRM IS 'Подтверждена ли сессии';
COMMENT ON COLUMN DNAUTHORIZATION.ACTIVE_SESSIONS.SESSION_TOKEN IS 'Токен сессии';
-- ТАБЛИЦА DNAUTHORIZATION.REFRESH_TOKENS
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.REFRESH_TOKENS
(
    SESSION_ACCOUNT_ID           UUID REFERENCES DNAUTHORIZATION.USERS_ACCOUNT (ACCOUNT_ID) NOT NULL,
    SESSION_REFRESH_TOKENS       TEXT UNIQUE                                                NOT NULL,
    SESSION_REFRESH_TOKENS_START TIMESTAMP DEFAULT CURRENT_TIMESTAMP                        NOT NULL
);
-- ДОБАВЛЕНИЕ КОММЕНТАРИЕВ К ТАБЛИЦЕ DNAUTHORIZATION.REFRESH_TOKENS И ЕЁ СТОЛБЦАМ
COMMENT ON TABLE DNAUTHORIZATION.REFRESH_TOKENS IS 'Таблица со списком долгоживущих токенов';
COMMENT ON COLUMN DNAUTHORIZATION.REFRESH_TOKENS.SESSION_ACCOUNT_ID IS 'Ид токена';
COMMENT ON COLUMN DNAUTHORIZATION.REFRESH_TOKENS.SESSION_REFRESH_TOKENS IS 'Токен обновления';
COMMENT ON COLUMN DNAUTHORIZATION.REFRESH_TOKENS.SESSION_REFRESH_TOKENS_START IS 'Дата выдача токена';
-- ТАБЛИЦА DNAUTHORIZATION.APP_LIST
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.APP_LIST
(
    APP_ID           UUID NOT NULL DEFAULT GEN_RANDOM_UUID() UNIQUE PRIMARY KEY,
    APP_NAME         TEXT NOT NULL UNIQUE,
    APP_SECRET       TEXT NOT NULL,
    APP_TOKEN_SECRET TEXT NOT NULL,
    APP_IMAGE        TEXT NOT NULL,
    REDIRECT_URL     TEXT NOT NULL
);
-- ДОБАВЛЕНИЕ КОММЕНТАРИЕВ К ТАБЛИЦЕ DNAUTHORIZATION.APP_LIST И ЕЁ СТОЛБЦАМ
COMMENT ON TABLE DNAUTHORIZATION.APP_LIST IS 'Таблица для списка приложений';
COMMENT ON COLUMN DNAUTHORIZATION.APP_LIST.APP_ID IS 'Уникальный идентификатор приложения';
COMMENT ON COLUMN DNAUTHORIZATION.APP_LIST.APP_SECRET IS 'Секрет приложения';
COMMENT ON COLUMN DNAUTHORIZATION.APP_LIST.APP_TOKEN_SECRET IS 'Секрет используемый для jwt выданных этому приложению';
COMMENT ON COLUMN DNAUTHORIZATION.APP_LIST.REDIRECT_URL IS 'Адрес редиректа на приложение';

INSERT INTO DNAUTHORIZATION.APP_LIST(APP_NAME, APP_SECRET, APP_TOKEN_SECRET, APP_IMAGE, REDIRECT_URL)
VALUES ('EDOX1', '123', '1234',
        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACFklEQVR42r1TzUoCURS+j+AjDOTcubrqEQYlaClGbSKQIIjUGmgf2ipo4zYIlPEB6g18hB5h6I9AjKkgpNG4nbMY7uBVT8Md/eCDwTnnfGe+78jmIXCFG5R5haWH+bxgW1hP5YJEvrnCIsqzn/dYLvTihsdSwWOGwBlqXrFFNkBhEDcAB8wQOCMxL6SKK1iYZOBaOXP7FfEe/mV/FjE8lURNzVKu0tvqDeb2K4boKrGtHoOh/bSreHxEg4H9hKsvW/YmviAaDO3Xj1E7vuUsdtOQmgeaHdr+7Kkf47Aiaq/bYt3i8nlLyGFV1Ni0ye+AcnzkyNGOWLno+56Q34eORM1Jk9/jAiFQxvw55itZBJzG2aiRZMjwYR4/9h3YOJuv/joQcpGO5sCsGwb3gb36V+sO2IMlBTI64fJ9N/0S2BPVl4gjG/aATRq8pb0gIqEs/9wX2EMRFnQ8Jj0rp8VAR0JbTjOQx5bFEFE971ENKpL5/5JRVbOc/voE9CjoSFJarohabB6ipl1TcdD8OeNy3OBpxEPUYMsw9oSF+ZDDLoFdYA/YpsV/T+2HOHMCcSR2Z9ENTK+B/RleLRbHWXjslCYdyTnwRolqvMWaNJYr0JFcoOWxGLFEW7PcHJO+3YlFKEKtsjxLRD5E4vNwkTC+wxq2Soy7wgKhYFb81wfLu2D5OgBCuWQk+Iy/sXVj6m9UJv28ywzwBzxk2ACtcnlEAAAAAElFTkSuQmCC',
        'http://gitlab.iedt.com.rzd/');

INSERT INTO DNAUTHORIZATION.APP_LIST(APP_NAME, APP_SECRET, APP_TOKEN_SECRET, APP_IMAGE, REDIRECT_URL)
VALUES ('EDOX2', '123', '1234',
        'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAACFklEQVR42r1TzUoCURS+j+AjDOTcubrqEQYlaClGbSKQIIjUGmgf2ipo4zYIlPEB6g18hB5h6I9AjKkgpNG4nbMY7uBVT8Md/eCDwTnnfGe+78jmIXCFG5R5haWH+bxgW1hP5YJEvrnCIsqzn/dYLvTihsdSwWOGwBlqXrFFNkBhEDcAB8wQOCMxL6SKK1iYZOBaOXP7FfEe/mV/FjE8lURNzVKu0tvqDeb2K4boKrGtHoOh/bSreHxEg4H9hKsvW/YmviAaDO3Xj1E7vuUsdtOQmgeaHdr+7Kkf47Aiaq/bYt3i8nlLyGFV1Ni0ye+AcnzkyNGOWLno+56Q34eORM1Jk9/jAiFQxvw55itZBJzG2aiRZMjwYR4/9h3YOJuv/joQcpGO5sCsGwb3gb36V+sO2IMlBTI64fJ9N/0S2BPVl4gjG/aATRq8pb0gIqEs/9wX2EMRFnQ8Jj0rp8VAR0JbTjOQx5bFEFE971ENKpL5/5JRVbOc/voE9CjoSFJarohabB6ipl1TcdD8OeNy3OBpxEPUYMsw9oSF+ZDDLoFdYA/YpsV/T+2HOHMCcSR2Z9ENTK+B/RleLRbHWXjslCYdyTnwRolqvMWaNJYr0JFcoOWxGLFEW7PcHJO+3YlFKEKtsjxLRD5E4vNwkTC+wxq2Soy7wgKhYFb81wfLu2D5OgBCuWQk+Iy/sXVj6m9UJv28ywzwBzxk2ACtcnlEAAAAAElFTkSuQmCC',
        'https://www.google.com/');