default:
  image: rootmen/gradle-docker-builder
  services:
    - docker:24.0.5-dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  
stages:
  - check
  - test
  - build-native
  - build-docker
  - deploy

check:
  image: rootmen/gradle-docker-builder
  stage: check
  script:
    - gradle spotlessCheck

test:
  image: rootmen/gradle-docker-builder
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - source/modules/submodules/submodules-authorization/database/build/reports/tests/test/index.html
    expire_in: 180 minutes
  only:
    - main
    - dev-release

build-native:
  image: rootmen/gradle-docker-builder
  stage: build-native
  script:
    - gradle :source:modules:module-rest-authorization-endpoint:build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
  artifacts:
    paths:
      - source/modules/module-rest-authorization-endpoint/build/module-rest-authorization-endpoint-1.0-SNAPSHOT-runner
      - source/modules/module-rest-authorization-endpoint/build/resources/*
    expire_in: 180 minutes
  only:
    - main


build-docker-rest-endpoint:
  image: rootmen/gradle-docker-builder
  stage: build-docker
  script:
    - cd ./source/modules/module-rest-authorization-endpoint
    - docker build -f ./src/main/docker/Dockerfile.native -t authorization-server/module-rest-authorization-endpoint:"$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" .
    - docker save authorization-server/module-rest-authorization-endpoint:"$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" -o authorization-server.module-rest-authorization-endpoint.tar
    - mkdir -p "$CI_PROJECT_DIR"/docker/images/
    - mv authorization-server.module-rest-authorization-endpoint.tar "$CI_PROJECT_DIR"/docker/images/
  artifacts:
    paths:
      - docker/images/authorization-server.module-rest-authorization-endpoint.tar
  only:
    - main

deploy-rest-endpoint:
  image: rootmen/gradle-docker-builder
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 700 ~/.sshuild-nativ
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd ./docker
    - touch .env
    - echo "IMAGE_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA" >> .env
    - cd ./..
    - scp ./docker/.env $SSH_USER@$VM_IPADDRESS:/opt/edox-authorization/
    - scp -r ./docker/* $SSH_USER@$VM_IPADDRESS:/opt/edox-authorization/
    - scp -r ./docker/images/* $SSH_USER@$VM_IPADDRESS:/opt/edox-authorization/images/
    - ssh $SSH_USER@$VM_IPADDRESS "/bin/bash -s" < ./docker/deployscript.sh
  only:
    - main