default:
  image: rootmen/gradle-docker-builder
  services:
    - docker:24.0.5-dind

variables:
  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

stages:
  - check
  - test
  - build-native
  - build-docker
  - deploy

check:
  image: rootmen/gradle-docker-builder
  stage: check
  script:
    - gradle spotlessApply > spotlessApply.txt
  artifacts:
    paths:
      - docker info
      - spotlessApply.txt
    expire_in: 180 minutes

test:
  image: rootmen/gradle-docker-builder
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - source/modules/submodules/submodules-database-repository/build/reports/tests/test/index.html
    expire_in: 180 minutes

build-native:
  image: rootmen/gradle-docker-builder
  stage: build-native
  script:
    - gradle :source:modules:module-rest-authorization-endpoint:build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
  artifacts:
    paths:
      - source/modules/module-rest-authorization-endpoint/build/module-rest-authorization-endpoint-1.0-SNAPSHOT-runner
      - source/modules/module-rest-authorization-endpoint/build/resources/*
    expire_in: 180 minutes
  only:
    - main


build-docker-rest-endpoint:
  image: rootmen/gradle-docker-builder
  stage: build-docker
  script:
    - cd ./source/modules/module-rest-authorization-endpoint
    - docker build -f ./src/main/docker/Dockerfile.native -t authorization-server/module-rest-authorization-endpoint:"$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" .
    - docker save authorization-server/module-rest-authorization-endpoint:"$CI_COMMIT_REF_NAME"-"$CI_COMMIT_SHORT_SHA" -o authorization-server.module-rest-authorization-endpoint.tar
    - mv authorization-server.module-rest-authorization-endpoint.tar ./../../../docker/images/
  artifacts:
    paths:
      - docker/images/authorization-server.module-rest-authorization-endpoint.tar
  only:
    - main

deploy-rest-endpoint:
  image: rootmen/gradle-docker-builder
  stage: deploy
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apk add --update openssh )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan $VM_IPADDRESS >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - cd ./docker
    - touch .env
    - echo "IMAGE_TAG=$CI_COMMIT_REF_NAME-$CI_COMMIT_SHORT_SHA" >> .env
    - scp ./.env $SSH_USER@$VM_IPADDRESS:/opt/edox-authorization/
    - scp ./* $SSH_USER@$VM_IPADDRESS:/opt/edox-authorization/
    - ssh $SSH_USER@$VM_IPADDRESS "/bin/bash -s" < deployscript.sh
  artifacts:
    paths:
      - docker/images/authorization-server.module-rest-authorization-endpoint.tar
  only:
    - main