image: alpine

# DinD service is required for Testcontainers
services:
  - name: docker:dind
    # explicitly disable tls to avoid docker startup interruption
    command: ["--tls=false"]

variables:
  # Instruct Testcontainers to use the daemon of DinD.
  DOCKER_HOST: "tcp://docker:2375"
  # Instruct Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""
  # Improve performance with overlayfs.
  DOCKER_DRIVER: overlay2

stages:
  - test
  - package

test:
  image: quay.io/quarkus/ubi-quarkus-mandrel-builder-image:jdk-21
  stage: test
  script:
    - chmod +x ./gradlew
    - ./gradlew test
