default:
  image: rootmen/gradle-docker-builder
  services:
    - docker:24.0.5-dind

variables:
  # When using dind service, you must instruct docker to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # If you're using GitLab Runner 12.7 or earlier with the Kubernetes executor and Kubernetes 1.6 or earlier,
  # the variable must be set to tcp://localhost:2375 because of how the
  # Kubernetes executor connects services to the job container
  # DOCKER_HOST: tcp://localhost:2375
  #
  DOCKER_HOST: tcp://docker:2375
  #
  # This instructs Docker not to start over TLS.
  DOCKER_TLS_CERTDIR: ""

stages:
  - check
  - test
  - build-native
  - build-docker
  - deploy

check:
  image: rootmen/gradle-docker-builder
  stage: check
  script:
    - gradle spotlessApply > spotlessApply.txt
  artifacts:
    paths:
      - docker info
      - spotlessApply.txt
    expire_in: 180 minutes

test:
  image: rootmen/gradle-docker-builder
  stage: test
  script:
    - gradle test
  artifacts:
    paths:
      - source/modules/submodules/submodules-database-repository/build/reports/tests/test/index.html
    expire_in: 180 minutes

build-native:
  image: rootmen/gradle-docker-builder
  stage: build-native
  script:
    - gradle build -Dquarkus.package.type=native -Dquarkus.native.container-build=true
  artifacts:
    paths:
      - source/modules/module-rest-endpoint/build/module-rest-endpoint-1.0-SNAPSHOT-runner
      - source/modules/module-rest-endpoint/build/resources/*
    expire_in: 180 minutes
  only:
    - main


build-docker:
  image: rootmen/gradle-docker-builder
  stage: build-docker
  script:
    - cd ./source/modules/module-rest-endpoint
    - docker build -f ./src/main/docker/Dockerfile.native -t authorization-server/module-rest-endpoint:${CI_COMMIT_REF_NAME} .
    - docker save authorization-server/module-rest-endpoint:${CI_COMMIT_REF_NAME} -o authorization-server.module-rest-endpoint.tar
  artifacts:
    paths:
      - /*authorization-server.module-rest-endpoint.tar
  only:
    - main
