version: "3.7"
name: "iert-authorization"
services:
  module-rest-authorization-endpoint:
    image: authorization-server/module-rest-authorization-endpoint:${IMAGE_TAG}
    hostname: module-rest-authorization-endpoint-service
    container_name: module-rest-authorization-endpoint-service
    restart: unless-stopped
    ports:
      - "53725:80"
    networks:
      - app-authorization
    labels:
      org.label-schema.group: "edox-authorization"