-- СОЗДАНИЕ СХЕМЫ
CREATE SCHEMA IF NOT EXISTS DNAUTHORIZATION;

-- ТАБЛИЦА DNAUTHORIZATION.USERS_ACCOUNT
CREATE TABLE IF NOT EXISTS DNAUTHORIZATION.USERS_ACCOUNT
(
    ACCOUNT_ID                      UUID PRIMARY KEY DEFAULT GEN_RANDOM_UUID(),
    ACCOUNT_NAME                    TEXT                                       NOT NULL UNIQUE,
    ACCOUNT_MAIL                    TEXT                                       NOT NULL UNIQUE,
    ACCOUNT_PASSWORD_VERIFIER       TEXT                                       NOT NULL,
    ACCOUNT_SALT                    TEXT                                       NOT NULL,
    ACCOUNT_LAST_PASSWORD_UPDATE    TIMESTAMP        DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACCOUNT_PASSWORD_RESET_INTERVAL INTEGER          DEFAULT 90                NOT NULL
);

INSERT INTO DNAUTHORIZATION.USERS_ACCOUNT(ACCOUNT_NAME, ACCOUNT_MAIL, ACCOUNT_PASSWORD_VERIFIER, ACCOUNT_SALT)
VALUES ('TEST', 'TEST', 'TEST', 'TEST');
INSERT INTO DNAUTHORIZATION.USERS_ACCOUNT(ACCOUNT_NAME, ACCOUNT_MAIL, ACCOUNT_PASSWORD_VERIFIER, ACCOUNT_SALT)
VALUES ('TEST2', 'TEST2', 'TEST2', 'TEST');
INSERT INTO DNAUTHORIZATION.USERS_ACCOUNT(ACCOUNT_NAME, ACCOUNT_MAIL, ACCOUNT_PASSWORD_VERIFIER, ACCOUNT_SALT)
VALUES ('TEST3', 'TEST3', 'TEST3', 'TEST3');
INSERT INTO DNAUTHORIZATION.USERS_ACCOUNT(ACCOUNT_ID, ACCOUNT_NAME, ACCOUNT_MAIL, ACCOUNT_PASSWORD_VERIFIER, ACCOUNT_SALT)
VALUES ('39f311a4-837e-4fff-b6bf-55cf2a7b04ad'::uuid,'TEST4', 'TEST4', 'TEST4', 'TEST4');
